backend/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import index_wallet


from app1.views import index_page, \
    index_news, \
    index_get, \
    index_set, \
    index_checkSettings, \
    upload_photo, \
    form_add, \
    form_email, \
    upload_file, \
    get_file, \
    index_make_default, \
    index_kafka_send, \
    index_kafka_get

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_page, name='indexPage'),
    path('make_default/', index_make_default, name='indexdef'),
    path('kafka_start/', index_kafka_send),
    path('kafka_get/', index_kafka_get),
    path('wallet/', index_wallet, name='indexWallet'),
    path('order/', include('orders.urls', namespace='orders')),
    path('form/add/<str:title>/<str:data>/', form_add, name='form_add'),
    path('form/email/<str:title>/<str:name>/<str:email>/<str:phone>/<str:company>/<str:message>', form_email, name='form_add'),
    path('user/', include('users.urls', namespace='users')),
    path('sitedata/', include('sitedata.urls', namespace='sitedata')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/djangoproject/users/urls.py
# @Aleksandr Kristal v0.0.1 || get user
from django.urls import path

from users.views import \
    index_form, \
    index_chat, \
    index_register, \
    index_recovery, \
    index_send_email, \
    index_get, \
    index_get_completeness, \
    index_get_partners
from users.views import \
    login, \
    registration, \
    profile, \
    logout, \
    chat, \
    addMessage


app_name = 'users'

urlpatterns = [
    path('form/', index_form),
    path('chat/', index_chat),
    path('register/', index_register),
    path('recovery/', index_recovery),
    path('sendemail/', index_send_email),
    path('get_partners/', index_get_partners),
    path('get/', index_get),
    path('completeness', index_get_completeness),
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('chat/', chat, name='chat'),
    path('addMessage/<str:chatAddress>/<str:value>/', addMessage, name='addMessage'),
]

backend/djangoproject/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User, Chat


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'newClass',
        'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'newClass',
        'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите адрес эл.почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'}), required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'}), required=False)
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'form-control'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')


class UserAddChatForm(UserChangeForm):
    second_user_login = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-add-chat', 'placeholder': 'Введите имя получателя'}))
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-add-chat', 'placeholder': 'Введите название чата'}))

    class Meta:
        model = Chat
        fields = ('second_user_login', 'title',)

backend/djangoproject/users/views.py
# @Aleksandr Kristal v0.0.4 || get user
import ast
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import auth, messages
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from app1.config import urlAdress, urlAddressGlobal
from users.models import Chat, Message, getToken, IpData, TgUser
from django.contrib.auth.models import User
from app1.views import \
    sendEmail, \
    sendEmailRecovery, \
    sendRegProofEmail, \
    kafka_send_email
from app1.config import \
    password_recovery, \
    password_recovery_title, \
    getRandomCode, \
    dictStatus
import os
from users.services import \
    get_user_token, \
    update_files, \
    send_recovery_link, \
    get_recovery_link, \
    send_email, \
    create_chat, \
    get_chats, \
    get_chat_messages, \
    send_message, \
    get_user, \
    check_completeness,\
    register_user, \
    get_all_sellers, \
    read_message, \
    read_chat
from users.forms import \
    UserLoginForm, \
    UserRegistrationForm, \
    UserProfileForm, \
    UserAddChatForm
from orders.models import Basket
from users.models import Data


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def addIp(request, functionNM):
    curIp = get_client_ip(request)
    print("curIp: ", curIp)
    if curIp[:4] != "192.":
        ipData = IpData()
        ipData.initIp(curIp=curIp)
        ipData.userName = request.user
        ipData.functionNM = functionNM
        ipData.save()


def ip_save(func):
    def wrapper(*args, **kwargs):
        print("userIp: ", get_client_ip(args[0]), str(func.__name__))
        addIp(args[0], str(func.__name__))
        result = func(*args, **kwargs)
        return result
    return wrapper


@csrf_exempt
def index_form(request):
    if request.method == 'POST':
        login = request.POST.get('user', '_')
        password = request.POST.get('pass', '_')
        return JsonResponse(get_user_token(login, password))
    return render(request, 'form/index.html')


@csrf_exempt
def index_get_partners(request):
    if request.method == 'POST':
        actionType = request.POST.get('actionType', '_')
        if actionType == "getAllSellers":
            seller_list = get_all_sellers()
            return JsonResponse(seller_list)
    return render(request, 'get/index_get_sellers.html')


@csrf_exempt
def index_recovery(request):
    if request.method == 'POST':
        actionType = request.POST.get('actionType', '_')
        if actionType == 'sendRecoveryLink':
            login = request.POST.get('user', '')
            return JsonResponse(send_recovery_link(
                login))
        elif actionType == 'getRecoveryLink':
            token = request.POST.get('token', '')
            pass1 = request.POST.get('pass1', '')
            pass2 = request.POST.get('pass2', '')
            return JsonResponse(get_recovery_link(
                token,
                pass1,
                pass2))
    return render(request, 'form/index_recovery.html')


@csrf_exempt
def index_send_email(request):
    if request.method == 'POST':
        actionType = request.POST['actionType']
        if actionType == 'sendEmail':
            title = request.POST.get('title', '')
            text = request.POST.get('text', '')
            email = request.POST.get('email', '')
            return JsonResponse(send_email(
                title,
                text,
                email))
    return render(request, 'form/index_send_email.html')


@ip_save
@login_required
def index_chat(request):
    if request.method == 'POST':
        form = UserAddChatForm(data=request.POST)
        if 'second_user_login' in request.POST.keys():
            print(request.POST)
            second_user_login = request.POST['second_user_login']
            filterSecond = User.objects.filter(username=second_user_login)
            title = ''
            if 'title' in request.POST.keys():
                title = request.POST['title']
            print()
            if len(filterSecond) == 1 and \
                    len(Chat.objects.filter(firstUserLogin=second_user_login,
                                            title=title)) == 0 and \
                    len(Chat.objects.filter(secondUserLogin=second_user_login,
                                            title=title)) == 0:
                secondUser = User.objects.get(username=second_user_login)
                newChat = Chat(firstUser=request.user,
                               secondUser=secondUser,
                               title=title,
                               visibility=1)
                newChat.save()
    chatList = list(Chat.objects.filter(firstUser=request.user)) + \
               list(Chat.objects.filter(secondUser=request.user))

    messageListStr = "["
    firstUserAddress = ""

    for chat in chatList:
        messages = Message.objects.filter(chat=chat)
        for message in messages:
            chatUserName = ""
            if chat.secondUser == request.user:
                chatUserName = chat.firstUser.username
                firstUserAddress = chatUserName
            else:
                chatUserName = chat.secondUser.username
                firstUserAddress = chatUserName
            res = "['"
            if message.owner == request.user:
                res += str(message.owner.username + "', '" + chatUserName + "', 0, '")
            else:
                res += str(message.owner.username + "', '" + chatUserName + "', 1, '")
            res += str(message.text + "', '" + message.date.strftime("%B %d, %Y") + "'],")
            messageListStr += res

    print("messageList ", messageListStr)
    print("+-+-===", urlAdress)
    context = {'form': UserAddChatForm(),
               'chatList': chatList,
               'messageList': messageListStr + "]",
               'currentUserName': request.user.username,
               'firstUserAddress': firstUserAddress,
               'urlAdress': urlAddressGlobal,
               'chat_js_include': 1}
    print(context)
    return render(
        request,
        'users/chat.html',
        context)


@csrf_exempt
def index_get(request):
    if request.method == 'POST':
        action = request.POST['action']
        if action == "GetUser":
            login = request.POST['login']
            return JsonResponse(get_user(login))
    return render(request, 'get/index_user.html')


@csrf_exempt
def index_get_completeness(request):
    if request.method == 'POST':
        action = request.POST['action']
        if action == "CheckCompleteness":
            login = request.POST['login']
            return JsonResponse(check_completeness(login))
    return render(request, 'get/index_completeness.html')


@csrf_exempt
def index_register(request):
    if request.method == 'POST':
        login = request.POST['log']
        password = request.POST['pass']
        role = request.POST['role']
        data = request.POST
        return JsonResponse(register_user(login, password, role, data))
    return render(request, 'register/index.html')


@csrf_exempt
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            userName = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=userName,
                                     password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect('/')
    else:
        form = UserLoginForm()
    context = {'form': UserLoginForm()}
    return render(request, 'users/login.html', context)


@csrf_exempt
def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            kafka_send_email("registration", f"Новая регистрация: {request.POST.get('email', 'xxx')}", "new")
            messages.success(request, 'Успешная регистрация')
            print(request.POST.keys())
            user = User.objects.get(username=request.POST['username'])
            data = Data(user=user,
                        walletVolume=0,
                        walletAddress="")
            data.save()
            return HttpResponseRedirect('/')
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


@ip_save
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user,
                               data=request.POST,
                               files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    # baskets = Basket.objects.filter(user=request.user)

    context = {'form': form,
               # 'baskets': baskets,
               'baskets': Basket.objects.all(),
               'volume': 123,#request.user.walletVolume / 10 ** 6,
               'address': "jksdlknsaldvknadksv"#request.user.walletAddress
               }
    return render(request,
                  'users/profile.html',
                  context)


@csrf_exempt
@ip_save
def index_wallet(request):
    return render(request)


@ip_save
def logout(request):
    return HttpResponseRedirect('/')


@ip_save
@login_required
def chat(request):
    return render(request, 'users/chat.html')


@ip_save
@login_required

backend/djangoproject/templates/users/chat.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


	 <div class="wrapper">
		<div class="box a">
            <div class="wrapperMini">
                <div class="boxMini a">
                    <form action="{% url 'users:chat' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="wrapperForm">
                            <div class="boxForm a">
                                <p>{{ form.second_user_login }}</p>
                            </div>
                            <!--<p>{{ form.title }}</p>-->
                            <div class="boxForm b" style="padding-top: 16px;">
                                <input type="submit" value="Начать общение" style="width: 10vw">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="boxMini b">
                    <div style="overflow: scroll; height: 50vh; width: 30vw;">
                        {% for item in chatList%}
                        <button onclick="addMessageTextArr('{% if currentUserName != item.secondUser.username %}{{ item.secondUser.username }}{% else %}{{ item.firstUser.username }}{% endif %}');" style="width: 30vw; background-color: #E8EDFE; color: black;margin-top: 10px;">
                        <p>
                            {{item.firstUser.username}} - {{item.secondUser.username}}
                        </p>
                        </button>
                        {% endfor %}
                    </div>
                </div></div>

        </div>
<!-- https://127.0.0.1:8000/user/addMessage/st2257/z -->
         <div class="box b">
            <div class="parent">
                <div class="child">
                    <div  style="background-color: #E9EBF1; width: 50vw; border-radius: 25px;">
                        <div style="overflow: scroll; height: 50vh; width: 50vw;" id="chatId"></div>
                        <div style="width: 50vw;">
                            <input autofocus="autofocus" id="textFieldId" type="text" style="width: 39.5vw;" placeholder="Your message">
                            <button onclick="addMessage()" style="width: 10vw;">send</button>
                        </div>
                        <form action="{% url 'users:chat' %}" method="post" enctype="multipart/form-data"></form>
                    </div>
                </div>
            </div>
         </div>
	</div>




<script>
  let currentUserName = "{{ firstUserAddress }}";
  element = document.getElementById("chatId");
  let text = "12222YouTube Chanel YouTube Chanel YouTube Chanel YouTube Chanel YouTube Chanel YouTube Chanel";
  let div1 = "<div class='child' style='width: 20vw; border-radius: 20px;"
  let div1var = "background-color: #E8EDFE;";
  let div2var = "background-color: #C6D1FC; margin-left: auto; margin-right: 0;";
  let div12 = "'><p style='padding: 1vh;'>";
  let div2 = "</p></div>";
  let msgArr = {{ messageList|safe }};

  const names = {
    "actionType": "",
    "data": "",
    "userAddress": currentUserName
    };

  function addMessage() {
    let textInput = document.getElementById("textFieldId").value;
    let div = document.createElement('divX');
    div.innerHTML = div1 + div2var + div12 + textInput + div2;
    element.append(div);
    document.getElementById("textFieldId").value = "";

    element.scrollTop = element.scrollHeight;
    document.getElementById("textFieldId").focus();

    names['data'] = textInput;
    console.log(String(window.location.href).slice(0, -5) + 'addMessage/' + names['userAddress'] + '/' + names['data']);
    console.log('https://127.0.0.1:8000/user/addMessage/' + names['userAddress'] + '/' + names['data']);
    console.log(String(window.location.href).slice(0, -5));

    urlByAddress = String(window.location.href).slice(0, -5) + 'addMessage/' + names['userAddress'] + '/' + names['data']
    // '{{ urlAdress }}/user/addMessage/' + names['userAddress'] + '/' + names['data']

    fetch(urlByAddress, {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
        },
    });

  }
    function addMessageText(text, user){
    let textInput = document.getElementById("textFieldId").value;
    let div = document.createElement('divX');
    if (user == 0) {
      div.innerHTML = div1 + div2var + div12 + text + div2;
    }
    else{
      div.innerHTML = div1 + div1var + div12 + text + div2;
    }
    element.append(div);
    document.getElementById("textFieldId").value = "";

    element.scrollTop = element.scrollHeight;
    document.getElementById("textFieldId").focus();
  }


  function addMessageTextArr(curUser) {
    names['userAddress'] = curUser;
    console.log(curUser);
    element.innerHTML = "";
       console.log(msgArr.length);
       for (let i = 0; i < msgArr.length; i++){
            console.log(i);
            if (curUser == msgArr[i][1]){
                addMessageText(msgArr[i][3], msgArr[i][2]);
            }
       }
  }
  addMessageTextArr("{{ firstUserAddress }}");
  element.scrollTop = element.scrollHeight;

</script>

{% endblock %}

backend/djangoproject/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


{% if form.non_field_errors %}
  <div class="non-field-errors">
    {% for err in form.non_field_errors %}
      <p class="form-error">{{ err }}</p>
    {% endfor %}
  </div>
{% endif %}




  <div class="login">
    <div class="login-screen">
      <div class="app-title">
        <h1>Login</h1>
      </div>

      <form action="{% url 'users:login' %}" method="post">
        {{ form.errors }}
      <div class="login-form">
        <div class="control-group">
          {{ form.username }}
        <label class="login-field-icon fui-user" for="login-name"></label>
        </div>

        <div class="control-group">
          {{ form.password }}
        <label class="login-field-icon fui-lock" for="login-pass"></label>
        </div>

        </form>

      <input class="btn btn-primary btn-large btn-block" type="submit" value="Login">
        <a class="login-link" href="#">Lost your password?</a>
      </div>
    </div>
  </div>


{% endblock %}

backend/djangoproject/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="parent">
    <div class="child">
        <h1>Profile</h1>
    </div>
</div>

<form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="parent">
        <div class="child">
            <p class="parent">First Name</p><p>{{ form.first_name }}</p>
        </div>

        <div class="child" style="padding-left: 20px;">
            <p class="parent">Last Name</p><p>{{ form.last_name }}</p>
        </div>
    </div>

    <div class="parent">
        <div class="child">
            <p class="parent">Image</p><p>{{ form.image }}</p>
        </div>
        <div class="child" style="padding-left: 20px;">
            <img width="250" src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'imgs/img.png' %}{% endif %}">
        </div>
    </div>


    <div class="parent">
        <div class="child">
            <p class="parent">Username</p><p>{{ form.username }}</p>
        </div>

        <div class="child" style="padding-left: 20px;">
            <p class="parent">Email</p><p>{{ form.email }}</p>
        </div>
    </div>

    <div class="parent">
        <div class="child">
            <input type="submit" value="Submit">
        </div>
        <div class="child" style="padding-left: 20px;">
            <a class="link" href="{% url 'users:logout' %}">
                <img width="50px", src="{% static 'imgs/icons/logout.png' %}">
            </a>
        </div>
    </div>
</form>



{% include 'order/baskets.html' %}

{% endblock %}

backend/djangoproject/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{{ form.errors  }}



 <div class="login">
    <div class="login-screen">
      <div class="app-title">
        <h1>Registration</h1>
      </div>

      <form action="{% url 'users:registration' %}" method="post">
        {{ form.errors }}
      <div class="login-form">

        <div class="control-group">
          {{ form.username }}
        <label class="login-field-icon fui-user" for="login-name"></label>
        </div>

        <div class="control-group">
          {{ form.password1 }}
        <label class="login-field-icon fui-lock" for="login-pass"></label>
        </div>


          <div class="control-group">
          {{ form.password2 }}
        <label class="login-field-icon fui-user" for="login-name"></label>
        </div>

        <div class="control-group">
          {{ form.first_name }}
        <label class="login-field-icon fui-lock" for="login-pass"></label>
        </div>

          <div class="control-group">
          {{ form.last_name }}
        <label class="login-field-icon fui-user" for="login-name"></label>
        </div>

        <div class="control-group">
          {{ form.email }}
        <label class="login-field-icon fui-lock" for="login-pass"></label>
        </div>


        </form>

      <input class="btn btn-primary btn-large btn-block" type="submit" value="Register">
      </div>
    </div>
  </div>

{% endblock %}

backend/djangoproject/templates/users/wallet.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="parent">
    <div class="child">
        <h1>Wallet</h1>
    </div>
</div>


<form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="parent">
        <input hidden type="text" name="typeAction" value="sendMoney">

        <div class="child" style="padding-left: 20px;">
            <p class="parent">Wallet Address: </p><p><input type="text" name="walletAddress"></p>
        </div>
        <div class="child" style="padding-left: 20px;">
            <p class="parent">Amount: </p><p><input type="number" min="0" max="1" step="0.001" name="amount"></p>
        </div>
    </div>

    <div class="parent">
        <div class="child">
            <p>My adress: {{ address }}</p>
        </div>
    </div>
    <div class="parent">
        <div class="child">
            <input type="submit" value="Balance: {{ volume }}">
        </div>
    </div>
    <div class="parent">
        <div class="child" style="padding-top: 20px; padding: 20px;">
            <input type="submit" value="Send TON">
        </div>
    </div>
</form>

{% endblock %}