backend/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import index_wallet


from app1.views import index_page, \
    index_news, \
    index_get, \
    index_set, \
    index_checkSettings, \
    upload_photo, \
    form_add, \
    form_email, \
    upload_file, \
    get_file, \
    index_make_default, \
    index_kafka_send, \
    index_kafka_get

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_page, name='indexPage'),
    path('make_default/', index_make_default, name='indexdef'),
    path('kafka_start/', index_kafka_send),
    path('kafka_get/', index_kafka_get),
    path('wallet/', index_wallet, name='indexWallet'),
    path('order/', include('orders.urls', namespace='orders')),
    path('form/add/<str:title>/<str:data>/', form_add, name='form_add'),
    path('form/email/<str:title>/<str:name>/<str:email>/<str:phone>/<str:company>/<str:message>', form_email, name='form_add'),
    path('user/', include('users.urls', namespace='users')),
    path('sitedata/', include('sitedata.urls', namespace='sitedata')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/djangoproject/orders/urls.py
from django.urls import path

from orders.views import index_order, basket_add, basket_remove, send_money

app_name = 'orders'

urlpatterns = [
    path('', index_order, name='index'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('baskets/send_money/<int:number>/', send_money, name='send_money'),
]

backend/djangoproject/users/urls.py
# @Aleksandr Kristal v0.0.1 || get user
from django.urls import path

from users.views import \
    index_form, \
    index_chat, \
    index_register, \
    index_recovery, \
    index_send_email, \
    index_get, \
    index_get_completeness, \
    index_get_partners
from users.views import \
    login, \
    registration, \
    profile, \
    logout, \
    chat, \
    addMessage


app_name = 'users'

urlpatterns = [
    path('form/', index_form),
    path('chat/', index_chat),
    path('register/', index_register),
    path('recovery/', index_recovery),
    path('sendemail/', index_send_email),
    path('get_partners/', index_get_partners),
    path('get/', index_get),
    path('completeness', index_get_completeness),
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('chat/', chat, name='chat'),
    path('addMessage/<str:chatAddress>/<str:value>/', addMessage, name='addMessage'),
]

backend/djangoproject/orders/models.py
from django.db import models
from django.contrib import admin
from users.models import User

# Create your models here.


class SubDivType(models.Model):
    shortName = models.CharField(max_length=128, blank=False)
    shortText = models.CharField(max_length=128, blank=False)
    fullText = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.shortName} {self.shortText}'


class OrderType(models.Model):
    subDivType = models.ForeignKey(to=SubDivType, on_delete=models.PROTECT)
    shortName = models.CharField(max_length=128, blank=False)
    shortText = models.CharField(max_length=128, blank=False)
    fullText = models.TextField(null=True, blank=True)
    averagePrice = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='orders_images')


class Order(models.Model):
    userId = models.IntegerField(default=0)
    orderType = models.ForeignKey(to=OrderType, on_delete=models.PROTECT)
    description = models.TextField(null=True, blank=True)
    orderPrice = models.DecimalField(max_digits=6, decimal_places=2)


class BasketQuerySet(models.QuerySet):
    def totalSum(self):
        return sum(basket.sum() for basket in self)

    def totalQuantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=OrderType, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.name} | Продукт'

    def sum(self):
        return self.product.averagePrice * self.quantity


@admin.register(Basket)
class DroneHubAdmin(admin.ModelAdmin):
    search_fields = ("id", "user", "product", "quantity", "created_timestamp", )
    list_display = ("id", "user", "product", "quantity", "created_timestamp")

backend/djangoproject/orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect
import os
import subprocess
from subprocess import check_output

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from orders.models import OrderType, Order, Basket
from django.contrib.auth.models import User
# from users.models import User
from users.views import \
    addIp, ip_save


@ip_save
@csrf_exempt
def index_order(request):
    print("=================================")
    if request.method == 'POST':
        pass
    orderType = OrderType.objects.all()
    arrContext = []
    for order in orderType:
        context = {"sale": "x1.5",
                   "price1": str(order.averagePrice),
                   "price2": str(order.averagePrice),
                   "title": order.shortName,
                   "id": order.id,
                   "url": 'imgs' + str(order.image.url)[6:]}
        print('imgs' + str(order.image.url)[6:])
        arrContext.append(context)
    return render(request, 'order/index.html',
                  context={"name": arrContext})


@ip_save
@login_required
def basket_add(request, product_id):
    product = OrderType.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@ip_save
@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@ip_save
@login_required
def send_money(request, number):
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

backend/djangoproject/templates/order/baskets.html
{% load static %}

<div class="parent">
    <div class="child">
        <h1>Basket</h1>
    </div>
</div>
{% if baskets %}

<table align="center" style="padding: 2vw;">
    <tr>
        <td>Name</td>
        <td style="padding-left: 2vw;">Description</td>
        <td style="padding-left: 2vw;">Price</td>
        <td style="padding-left: 2vw;">Quantity</td>
        <td style="padding-left: 2vw;">Sum</td>
        <td style="padding-left: 2vw;">Action</td>
    </tr>


{% for basket in baskets %}
    <tr style="padding-top: 30px;">
        <td>{{ basket.product.shortName }}</td>
        <td style="padding-left: 2vw;">{{ basket.product.shortText }}</td>
        <td style="padding-left: 2vw;">{{ basket.product.averagePrice }}</td>
        <td style="padding-left: 2vw;">{{ basket.quantity }}</td>
        <td style="padding-left: 2vw;">{{ basket.sum }}</td>
        <td style="padding-left: 2vw;">
            <a class="link" href="{% url 'orders:basket_remove' basket.id %}">
                <img width="50px", src="{% static 'imgs/icons/basket.png' %}">
            </a>
        </td>
    </tr>

{% endfor %}
    </table>


<div class="parent">
    <div class="child">
        <p style="font-size: 24px;">Total Sum: {{ baskets.totalSum }} Total Quantity: {{ baskets.totalQuantity }}</p>
    </div>
</div>
<div class="parent" style=" padding-bottom: 2vw;">
    <div class="child">
            <button style="width: 200px;">Order Chart</button>
    </div>
</div>

{% else %}
<p>item number: 0</p>
{% endif %}

backend/djangoproject/templates/order/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<div class="cards">
  {% for item in name %}
  <div class="card">
  <div class="card__top">
    <a href="#" class="card__image">
      <img src="{% static item.url %}" alt="Apple IPhone 14 PRO Max Gold"/>
    </a>
    <div class="card__label">{{ item.sale }}</div>
  </div>
  <div class="card__bottom">
    <div class="card__prices">
      <div class="card__price card__price--discount">{{ item.price1 }}</div>
      <div class="card__price card__price--common">{{ item.price2 }}</div>
    </div>
    <a href="#" class="card__title">{{ item.title }}</a>
      <form action="{% url 'orders:basket_add' item.id %}">
        <button class="card__add">В корзину</button>
      </form>
      <p></p>
  </div>
</div>
  {% endfor %}

</div>

{% else %}
    <a class="link" href="{% url 'users:login' %}">Go to login</a>
    <a class="link" href="{% url 'users:registration' %}">Go to registration</a>
{% endif %}
{% endblock %}