backend/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import index_wallet


from app1.views import index_page, \
    index_news, \
    index_get, \
    index_set, \
    index_checkSettings, \
    upload_photo, \
    form_add, \
    form_email, \
    upload_file, \
    get_file, \
    index_make_default, \
    index_kafka_send, \
    index_kafka_get

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_page, name='indexPage'),
    path('make_default/', index_make_default, name='indexdef'),
    path('kafka_start/', index_kafka_send),
    path('kafka_get/', index_kafka_get),
    path('wallet/', index_wallet, name='indexWallet'),
    path('order/', include('orders.urls', namespace='orders')),
    path('form/add/<str:title>/<str:data>/', form_add, name='form_add'),
    path('form/email/<str:title>/<str:name>/<str:email>/<str:phone>/<str:company>/<str:message>', form_email, name='form_add'),
    path('user/', include('users.urls', namespace='users')),
    path('sitedata/', include('sitedata.urls', namespace='sitedata')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/djangoproject/orders/urls.py
from django.urls import path

from orders.views import index_order, basket_add, basket_remove, send_money

app_name = 'orders'

urlpatterns = [
    path('', index_order, name='index'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('baskets/send_money/<int:number>/', send_money, name='send_money'),
]

backend/djangoproject/users/urls.py
# @Aleksandr Kristal v0.0.1 || get user
from django.urls import path

from users.views import \
    index_form, \
    index_chat, \
    index_register, \
    index_recovery, \
    index_send_email, \
    index_get, \
    index_get_completeness, \
    index_get_partners
from users.views import \
    login, \
    registration, \
    profile, \
    logout, \
    chat, \
    addMessage


app_name = 'users'

urlpatterns = [
    path('form/', index_form),
    path('chat/', index_chat),
    path('register/', index_register),
    path('recovery/', index_recovery),
    path('sendemail/', index_send_email),
    path('get_partners/', index_get_partners),
    path('get/', index_get),
    path('completeness', index_get_completeness),
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('chat/', chat, name='chat'),
    path('addMessage/<str:chatAddress>/<str:value>/', addMessage, name='addMessage'),
]

backend/djangoproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static '/css2/main.css' %}" rel="stylesheet">
    <link href="{% static '/css2/header.css' %}" rel="stylesheet">
    <link href="{% static '/css2/footer.css' %}" rel="stylesheet">
    <link href="{% static '/css2/test/index.css' %}" rel="stylesheet">
    <link href="{% static '/css2/test/basket.css' %}" rel="stylesheet">
    {% if chat_js_include %}
        <link href="{% static '/css2/chat/main.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static '/js/chat/main.js' %}"></script>
    {% endif %}
</head>
<body>

    <div id="header-img">
        <img style="min-height: 30vh; min-width: 100vw;" src="{% static '/imgs/israel_iran_wall_Zoonar_Alamy.jpg' %}">
    </div>

    <ul id="nav-bar">
        <li><a style="font-size: 20px;" class="link" href="{% url 'indexPage' %}">News</a></li>
        <li><a style="font-size: 20px;" class="link" href="{% url 'orders:index' %}">Bets</a></li>
        <li><a style="font-size: 20px;" class="link" href="#">Analytics</a></li>
        {% if user.is_authenticated %}
            <li style="float: right;"><a style="font-size: 20px;" class="link" href="{% url 'users:profile' %}">Profile</a></li>
            <li style="float: right;"><a style="font-size: 20px;" class="link" href="{% url 'indexWallet' %}">Wallet</a></li>
            <li style="float: right;"><a style="font-size: 20px;" class="link" href="{% url 'users:chat' %}">&#9993;</a></li>
        {% else %}
            <li style="float: right;"><a style="font-size: 20px;" class="link" href="{% url 'users:login' %}">Login</a></li>
            <li style="float: right;"><a style="font-size: 20px;" class="link" href="{% url 'users:registration' %}">Register</a></li>
        {% endif %}

        {% if user.is_superuser or user.is_staff %}
            <li style="float: right;"><a style="font-size: 20px;" class="link" href="{% url 'admin:index' %}">Admin</a></li>
        {% endif %}
    </ul>



{% block nav %}{% endblock %}
{% block content %}{% endblock %}
{% block footer %}{% endblock %}


   <footer style="padding-top: 100px;">
      <div class="footer-body">

          <div> <p>WarWise Analytics Betting</p>
              <div style="display: flex;">
                  <a href="https://t.me/militarybetbot"
                     style="color: white; text-decoration: none; padding: 10px;">
                      <div class="child" style="width: 10vw; background-color: #202793; border-radius: 20px;">
                          <p>Telegram Bot</p>
                          <img width="50" src="{% static '/tgimgs/bot.png' %}" style="border-radius: 25px;">
                      </div>
                  </a>
                  <a href="https://t.me/globalcompas"
                     style="color: white; text-decoration: none; padding: 10px;">
                      <div class="child" style="width: 10vw; background-color: #202793; border-radius: 20px;">
                          <p>Telegram Chanel</p>
                          <img width="50" src="{% static '/tgimgs/compas.png' %}" style="border-radius: 25px;">
                      </div>
                  </a>
                  <a href="https://www.youtube.com/@GlobalCompas"
                     style="color: white; text-decoration: none; padding: 10px;">
                      <div class="child" style="width: 10vw; background-color: #202793; border-radius: 20px;">
                        <p>YouTube Chanel</p>
                        <img width="50" src="{% static '/tgimgs/youtube.jpeg' %}" style="border-radius: 25px;">
                      </div>
                  </a>
              </div>
          </div>
         <div>
            <p> These names convey the combination of military analytics and betting in a professional and serious manner. </p>
            <ul>
               <li><a href="#"> About </a></li>
               <li><a href="#"> Contact </a></li>
               <li><a href="#"> Terms & Conditions </a></li>
               <li><a href="#"> Privacy Policy </a></li>
            </ul>
         </div>
      </div>
      <div class="footer-copyright">
          <div class="parent">
            <div class="child">
                ©Aleksandr Kristal
            </div>
          </div>
      </div>
   </footer>

</body>
</html>

backend/djangoproject/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div id="content" style="padding-left: 10vw; padding-right: 10vw;">
      <table><tr><td>
      <div>
        <h1>Predictive Analytics Redefining Warfare</h1>
        <div style="padding-left: 5vw; padding-right: 5vw;">
          <p style="font-size: 18px; line-height: 3vh+4vw;">
            <img src="/static/imgs/news/new1.png"
                 style="border-radius: 20px; padding: 10px; float:left;"
                 width="200"
                 height="200"
                 alt="Иллюстрация" align="left"> The integration of sophisticated predictive analytics algorithms and machine learning technologies has empowered military strategists to anticipate and assess potential conflict scenarios with unprecedented precision. This predictive capability is enabling proactive decision-making and strategic planning, significantly enhancing the effectiveness of defense operations.</p>
        </div>
      </div></td></tr></table>

      <table><tr><td>
      <div style="margin-top: 10px;">
        <h1>Real-time Threat Assessment</h1>
        <div style="padding-left: 5vw; padding-right: 5vw;">
          <p style="font-size: 18px; line-height: 3vh+4vw;">
            <img src="/static/imgs/news/new2.jpg"
                 style="border-radius: 20px; padding: 10px; float:right;"
                 width="200"
                 height="200"
                 alt="Иллюстрация" align="left"> Advanced war analytics platforms are now capable of processing vast volumes of real-time data, ranging from geopolitical developments to battlefield intelligence. This real-time threat assessment capability equips military leaders with actionable insights, enabling agile responses to dynamic and evolving security challenges.</p>
        </div>
      </div></td></tr></table>


      <table><tr><td>
      <div style="margin-top: 10px;">
        <h1>Optimized Resource Allocation</h1>
        <div style="padding-left: 5vw; padding-right: 5vw;">
          <p style="font-size: 18px; line-height: 3vh+4vw;">
            <img src="/static/imgs/news/new3.png"
                 style="border-radius: 20px; padding: 10px; float:left;"
                 width="200"
                 height="200"
                 alt="Иллюстрация" align="left">The application of data-driven analytics in war planning has facilitated optimized resource allocation, ensuring that military assets and personnel are strategically deployed to maximize operational efficiency and minimize risks. This strategic resource allocation is poised to redefine the cost-effectiveness and tactical agility of defense initiatives.</p>
        </div>
      </div></td></tr></table>


      <table><tr><td>
      <div style="margin-top: 10px;">
        <h1>Ethical Considerations and Accountability</h1>
        <div style="padding-left: 5vw; padding-right: 5vw;">
          <p style="font-size: 18px; line-height: 3vh+4vw;">
            <img src="/static/imgs/news/new4.webp"
                 style="border-radius: 20px; padding: 10px; float:right;"
                 width="200"
                 height="200"
                 alt="Иллюстрация" align="left">As war analytics continues to evolve, there is an increasing emphasis on ethical considerations and accountability in the utilization of data-driven insights for military purposes. The ethical implications of leveraging predictive analytics in conflict resolution and the responsible use of algorithmic decision-making are emerging as critical areas of debate and scrutiny.</p>
        </div>
      </div></td></tr></table>


      <table><tr><td>
      <div style="margin-top: 10px;">
        <h1>Breaking News: Groundbreaking Developments in War Analytics</h1>
        <div style="padding-left: 5vw; padding-right: 5vw;">
          <p style="font-size: 18px; line-height: 3vh+4vw;">
            <img src="/static/imgs/news/new5.webp"
                 style="border-radius: 20px; padding: 10px; float:left;"
                 width="200"
                 height="200"
                 alt="Иллюстрация" align="left">In a groundbreaking development, the field of war analytics has witnessed a major breakthrough, revolutionizing the way military strategies are formulated and executed. Cutting-edge advancements in data analysis and predictive modeling have paved the way for a new era in warfare, with profound implications for global security and defense operations.</p>
        </div>
      </div></td></tr></table>
  </div>
{% endblock %}